app_id: "2e0b5660-f820-45f7-b554-021e4ed4d565"
app_secret: "HOF.k2AQ7_QUbEEcfRC46Y1z_775t.GC8X"
redirect: "http://localhost:8000/callback"
scopes: "openid profile offline_access user.read calendars.read"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"