app_id: "xxx"
app_secret: "xxx"
#need to keep same as https://portal.azure.com/?l=en.en-us#blade/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/Authentication/appId/2e0b5660-f820-45f7-b554-021e4ed4d565/isMSAApp/
#localhost for test
redirect: "http://localhost:8000/callback"
scopes: "openid profile offline_access user.read calendars.readwrite mail.send"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"



